services:
  nginx:
    # image: nginx
    build: ./requirements/nginx
    # build:
    #   context: ./requirements/nginx/
    #   dockerfile: Dockerfile

    ports:
      - 80:80
      - 443:443

    volumes:
      # nginx configuration
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
      # Where the files are stored
      - ./requirements/tools/website/:/var/www/
    
    # depends_on:
    #   - wordpress
  
  # wordpress + php-fpm
  wordpress:
    image: php:7-fpm
    # build: ./requirements/wordpress
    volumes:
      - ./requirements/tools/website/:/var/www/

# //TODO:
# networks:
#   - inception