version: '3'
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    volumes:
      - vol_wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
  
  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - vol_wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    env_file:
      - .env
    restart: always
    build: ./requirements/mariadb
    volumes:
      - vol_mysql:/var/lib/mysql
    networks:
      - inception

volumes:
  vol_wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/hello/data/wordpress
      o: bind
    name: vol_wordpress
  
  vol_mysql:
    driver: local
    driver_opts:
      type: none
      device: /home/hello/data/mysql
      o: bind
    name: vol_mysql

networks:
  inception:
    driver: bridge
