services:
  nginx:
    # image: nginx
    # build: ./nginx
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile

    ports:
      - 80:80
      - 443:443

    volumes:
      # nginx configuration
      - ./requirements/nginx/:/etc/nginx
      # Where the files are stored
      - ./requirements/nginx/nginx-html/:/var/www/
  
  # wordpress + php-fpm
  # wpf:
  #   build: ./wpf
