services:
  nginx:
    # image: nginx
    build: ./nginx
    # build:
    #   context: ./nginx/
    #   dockerfile: Dockerfile

    ports:
      - 80:80
    volumes:
      -./nginx/nginx-html/:/usr/share/nginx/html